
INSERT INTO PRODUCT VALUES(1, '신발', '나이키 신발', 10000, 'S');
INSERT INTO PRODUCT VALUES(2, '가방', '구찌 가방', 10000, 'S');
INSERT INTO PRODUCT VALUES(3, '티셔츠', '맘에 드는 티셔츠', 10000, 'S');
INSERT INTO PRODUCT VALUES(4, '바지', '가을 남자 바지', 10000, 'S');
INSERT INTO PRODUCT VALUES(5, '모자', '가을 남자 모자', 10000, 'S');
INSERT INTO PRODUCT VALUES(6, '반지', '아내를 위한 반지', 10000, 'S');
INSERT INTO PRODUCT VALUES(7, '티셔츠 1+1', '[1+1행사] 맘에 드는 티셔츠', 10000, 'E');
INSERT INTO PRODUCT VALUES(8, '바지 + 모자 묶음', '[묶음상품] 가을 남자 바지, 모자 셋트', 15000, 'G');
INSERT INTO PRODUCT VALUES(9, '가방 옵션구매상품', '[딜상품] 구찌 가방 사면, 신발 50%할인', 10000, 'D');

INSERT INTO PRODUCT_GROUP VALUES(1, 9, 1);
INSERT INTO PRODUCT_GROUP VALUES(2, 9, 2);
INSERT INTO PRODUCT_GROUP VALUES(3, 8, 4);
INSERT INTO PRODUCT_GROUP VALUES(4, 8, 5);

