DROP TABLE PRODUCT IF EXISTS ;

CREATE TABLE PRODUCT(
    PRODUCT_CODE INTEGER NOT NULL,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_DESC VARCHAR(255),
    PRODUCT_PRICE DECIMAL(12),
    PRODUCT_TYPE CHAR(1) DEFAULT 'S',
    PRIMARY KEY (PRODUCT_CODE)
);

DROP TABLE PRODUCT_GROUP IF EXISTS ;

CREATE TABLE PRODUCT_GROUP(
    PRODUCT_GROUP_SEQ INTEGER NOT NULL,
    PARENT_PRODUCT_CODE INTEGER,
    PRODUCT_CODE INTEGER,
    PRIMARY KEY (PRODUCT_GROUP_SEQ)
);