DROP TABLE PRODUCT IF EXISTS ;

CREATE TABLE PRODUCT(
    PRODUCT_CODE INTEGER NOT NULL,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_DESC VARCHAR(255),
    PRODUCT_PRICE DECIMAL(12),
    PRODUCT_TYPE CHAR(1) DEFAULT 'S',
    PRIMARY KEY(PRODUCT_CODE)
);